CC	= g++
LD	= g++

CCFLAGS	= -O0 -g -c `root-config --cflags`
LDFLAGS	= `root-config --libs`

fitkptherm: fitkptherm.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkptherm.o: fitkptherm.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkptheorysir: fitkptheorysir.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkptheorysir.o: fitkptheorysir.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkptheorysircent: fitkptheorysircent.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkptheorysircent.o: fitkptheorysircent.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkptheorysircentall: fitkptheorysircentall.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkptheorysircentall.o: fitkptheorysircentall.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkptheorysircentallwgt: fitkptheorysircentallwgt.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkptheorysircentallwgt.o: fitkptheorysircentallwgt.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgt: fitkpalltheorysircentallwgt.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgt.o: fitkpalltheorysircentallwgt.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgtbgfix: fitkpalltheorysircentallwgtbgfix.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgtbgfix.o: fitkpalltheorysircentallwgtbgfix.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgtbgfixppcs: fitkpalltheorysircentallwgtbgfixppcs.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgtbgfixppcs.o: fitkpalltheorysircentallwgtbgfixppcs.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgtbgfixnewal: fitkpalltheorysircentallwgtbgfixnewal.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgtbgfixnewal.o: fitkpalltheorysircentallwgtbgfixnewal.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgtbgfixnewalppcs: fitkpalltheorysircentallwgtbgfixnewalppcs.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgtbgfixnewalppcs.o: fitkpalltheorysircentallwgtbgfixnewalppcs.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallwgtbgfixnewalppcsflt: fitkpalltheorysircentallwgtbgfixnewalppcsflt.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallwgtbgfixnewalppcsflt.o: fitkpalltheorysircentallwgtbgfixnewalppcsflt.cxx
	$(CC) $^ -o $@ $(CCFLAGS)

fitkpalltheorysircentallfltbgfixnewalppcsflt: fitkpalltheorysircentallfltbgfixnewalppcsflt.o
	$(CC) $^ -o $@ $(LDFLAGS)

fitkpalltheorysircentallfltbgfixnewalppcsflt.o: fitkpalltheorysircentallfltbgfixnewalppcsflt.cxx
	$(CC) $^ -o $@ $(CCFLAGS)
